// Generated by scripts/gen-test-keys.mjs — test-only keys, not secret.
export const OWNER_JWK_X = 'vTATqI_PhMqFuJ-a_sVNW6Cz0NtL1_dVW6bGA-e-PmM';
export const OWNER_JWK_D = 'yKmNyAyQ4c8RWcsuUyYdHuU9b71AVLPTatUQOUZfkJI';
export const OWNER_PUBKEY_B64 = 'vTATqI/PhMqFuJ+a/sVNW6Cz0NtL1/dVW6bGA+e+PmM=';

